[package]
name = "RSL"
authors = ["Jose Storopoli<thestoropoli@gmail.com>"]
version = "0.1.0"
edition = "2018"
license = "MIT"
description = "Concatenates 2 CSVs files from Scopus and Web of Science by DOI and TITLE"
crate-type = "bin"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = "0.15.1"
clap = "3.0.0-beta.4"
